@baseURL = http://localhost:3001

### Create Student
POST {{baseURL}}/students
Content-Type: application/json

{
  "name": "John Doe",
  "course": "Computer Science"
}

### List All Students
GET {{baseURL}}/students
Content-Type: application/json

### Update Student by ID
PUT {{baseURL}}/students/ab3f60fb-e27c-40a6-8628-4c90b5036136
Content-Type: application/json

{
  "name": "John Doe atualizado",
  "course": "Computer Science atualizado"
}

### Delete Student by ID
DELETE {{baseURL}}/students/ab3f60fb-e27c-40a6-8628-4c90b5036136
Content-Type: application/json